#!/bin/bash

set -ex

# Don't push images if branch is not master
echo "Current Branch: $SOURCE_BRANCH"
if [ "${SOURCE_BRANCH}" != "master" ]; then
    exit 0
fi

for tag in $(sudo docker images michaukrieg/node-opencascade --format "{{.Tag}}");
do
    docker push "michaukrieg/node-opencascade:${tag}"
done