name: Build and publish

on:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches: [master]

env:
  IMAGE_NAME: node-opencascade
  OCCT_VERSION: V7_6_2

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        node: [14, 16]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            node_version=${{ matrix.node }}
            occt_version=${{ env.OCCT_VERSION }}
          tags: |
            michaukrieg/${{ env.IMAGE_NAME }}:node-${{matrix.node}}
            michaukrieg/${{ env.IMAGE_NAME }}:${{ env.OCCT_VERSION }}-node-${{ matrix.node }}
            ghcr.io/michsior14/${{ env.IMAGE_NAME }}:node-${{matrix.node}}
            ghcr.io/michsior14/${{ env.IMAGE_NAME }}:${{ env.OCCT_VERSION }}-node-${{ matrix.node }}
